"""
app.py — Main Streamlit Dashboard for the Sales Revenue Forecasting System.

Loads data from data/dataset/ and routes to individual page modules.
Launch with:  python main.py  OR  streamlit run app/app.py
"""

import sys
import json
import streamlit as st
import pandas as pd
from pathlib import Path

# ── Paths ──────────────────────────────────────────────────────────────────────
APP_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = APP_DIR.parent
DATASET_DIR = PROJECT_ROOT / "data" / "dataset"
PREDICTIONS_DIR = PROJECT_ROOT / "data" / "predictions"
MODELS_DIR = PROJECT_ROOT / "outputs" / "models"

if str(APP_DIR) not in sys.path:
    sys.path.insert(0, str(APP_DIR))

# ── Page Config (MUST be first Streamlit call) ────────────────────────────────
st.set_page_config(
    page_title="SalesPulse — Revenue Forecast",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Load Custom CSS ───────────────────────────────────────────────────────────
css_path = APP_DIR / "styles.css"
if css_path.is_file():
    with open(css_path) as f:
        st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

# ── Imports ───────────────────────────────────────────────────────────────────
from components.sidebar import render_sidebar
from views import home, sales_analysis, forecast, product_analysis
from views import revenue_analysis, model_comparison, reports, sustainability


# ── Data Loaders (cached) ────────────────────────────────────────────────────

@st.cache_data(show_spinner="Loading daily sales data...")
def load_daily_sales() -> pd.DataFrame:
    """Loads total_daily_sales.csv — the main dataset."""
    path = DATASET_DIR / "total_daily_sales.csv"
    if path.is_file():
        df = pd.read_csv(path)
        df["date"] = pd.to_datetime(df["date"])
        return df
    return pd.DataFrame()


@st.cache_data(show_spinner="Loading featured data...")
def load_featured_sales() -> pd.DataFrame:
    """Loads featured_daily_sales.csv with lag/rolling features."""
    path = DATASET_DIR / "featured_daily_sales.csv"
    if path.is_file():
        df = pd.read_csv(path)
        df["date"] = pd.to_datetime(df["date"])
        return df
    return pd.DataFrame()


@st.cache_data(show_spinner="Loading evaluation metrics...")
def load_eval_metrics() -> dict:
    """Loads official model metrics, preferring the training pipeline CSV."""
    path2 = MODELS_DIR / "evaluation_metrics.csv"
    if path2.is_file():
        df = pd.read_csv(path2)
        return {
            row["Model"]: {
                "MAE": row.get("MAE", 0),
                "RMSE": row.get("RMSE", 0),
                "MAPE": row.get("MAPE (%)", 0),
                "R2 Score": row.get("R2 Score", None),
            }
            for _, row in df.iterrows()
        }

    path1 = DATASET_DIR / "evaluation_metrics.json"
    if path1.is_file():
        with open(path1) as f:
            return json.load(f)

    return {}


@st.cache_data(show_spinner="Loading plot data...")
def load_plot_data() -> dict:
    """Loads plot_data.json — actuals + multi-model predictions for 30 days."""
    # Prefer training-generated outputs, then fall back to bundled demo data.
    path1 = PREDICTIONS_DIR / "plot_data.json"
    path2 = DATASET_DIR / "plot_data.json"

    for path in [path1, path2]:
        if path.is_file():
            with open(path) as f:
                return json.load(f)
    return {}


@st.cache_data(show_spinner="Loading product forecasts...")
def load_product_forecasts() -> dict:
    """Loads product_forecasts.json — per-product predictions."""
    path = DATASET_DIR / "product_forecasts.json"
    if path.is_file():
        with open(path) as f:
            return json.load(f)
    return {}


@st.cache_data(show_spinner="Loading top products...")
def load_top_products() -> pd.DataFrame:
    """Loads top_50_products.csv."""
    path = DATASET_DIR / "top_50_products.csv"
    if path.is_file():
        return pd.read_csv(path)
    return pd.DataFrame()


@st.cache_data(show_spinner="Loading top 5 products daily...")
def load_top5_daily() -> pd.DataFrame:
    """Loads top_5_products_daily.csv."""
    path = DATASET_DIR / "top_5_products_daily.csv"
    if path.is_file():
        df = pd.read_csv(path)
        df["date"] = pd.to_datetime(df["date"])
        return df
    return pd.DataFrame()


@st.cache_data(show_spinner="Loading forecast data...")
def load_forecast_csv() -> pd.DataFrame:
    """Loads forecast.csv from predictions dir (generated by training pipeline)."""
    path = PREDICTIONS_DIR / "forecast.csv"
    if path.is_file():
        df = pd.read_csv(path)
        if "date" in df.columns:
            df["date"] = pd.to_datetime(df["date"])
        return df
    return pd.DataFrame()


@st.cache_data(show_spinner="Loading model metrics CSV...")
def load_metrics_csv() -> pd.DataFrame:
    """Loads evaluation_metrics.csv from outputs/models/."""
    path = MODELS_DIR / "evaluation_metrics.csv"
    if path.is_file():
        return pd.read_csv(path)
    return pd.DataFrame()


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    # Load all data
    daily_df = load_daily_sales()
    featured_df = load_featured_sales()
    eval_metrics = load_eval_metrics()
    plot_data = load_plot_data()
    product_forecasts = load_product_forecasts()
    top_products = load_top_products()
    top5_daily = load_top5_daily()
    forecast_csv = load_forecast_csv()
    metrics_csv = load_metrics_csv()

    # Empty state
    if daily_df.empty:
        st.markdown(
"""<div class="page-title-container">
    <div class="page-title">Welcome to SalesPulse</div>
    <div class="page-subtitle">No data found in data/dataset/ — please add your CSV files.</div>
</div>""",
            unsafe_allow_html=True,
        )
        st.info("Place your dataset files in `data/dataset/` and restart the app.")
        return

    # Sidebar
    sidebar_state = render_sidebar(daily_df)
    active_page = sidebar_state["page"]
    filters = sidebar_state["filters"]

    # Apply year filter if set
    filtered_df = daily_df.copy()
    if filters.get("year"):
        filtered_df = filtered_df[filtered_df["year"] == filters["year"]]

    # ── Page Router ──────────────────────────────────────────
    if active_page == "Home":
        home.render(filtered_df, eval_metrics, plot_data)

    elif active_page == "Sales Analysis":
        sales_analysis.render(filtered_df)

    elif active_page == "Forecast":
        forecast.render(filtered_df, plot_data, forecast_csv, eval_metrics)

    elif active_page == "Product Analysis":
        product_analysis.render(top_products, top5_daily, product_forecasts)

    elif active_page == "Revenue Analysis":
        revenue_analysis.render(filtered_df, featured_df)

    elif active_page == "Model Comparison":
        model_comparison.render(eval_metrics, metrics_csv)

    elif active_page == "Reports":
        reports.render(filtered_df, eval_metrics, plot_data, forecast_csv)

    elif active_page == "Sustainability":
        sustainability.render(filtered_df, product_forecasts)


if __name__ == "__main__":
    main()
